---
version: 2
# opt in to updates for ecosystems that are not yet GA.
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-deps:
        patterns:
          - '*'
    commit-message:
      prefix: 'chore(deps): '

  # Maintain dependencies for Docker
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      docker-deps:
        patterns:
          - '*'
    commit-message:
      prefix: 'chore(deps): '

  # Maintain dependencies for Docker Compose
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
    groups:
      docker-compose-deps:
        patterns:
          - '*'
    commit-message:
      prefix: 'chore(deps): '

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-major]
    commit-message:
      prefix: 'chore(deps): '
    open-pull-requests-limit: 5
